# EDA

In [48]:
pip install google-cloud-bigquery pandas

Collecting google-cloud-bigquery
  Downloading google_cloud_bigquery-3.38.0-py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: pandas in c:\users\valentina\appdata\local\programs\python\python313\lib\site-packages (2.3.2)
Collecting google-api-core<3.0.0,>=2.11.1 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading google_api_core-2.28.1-py3-none-any.whl.metadata (3.3 kB)
Collecting google-auth<3.0.0,>=2.14.1 (from google-cloud-bigquery)
  Downloading google_auth-2.42.1-py2.py3-none-any.whl.metadata (6.6 kB)
Collecting google-cloud-core<3.0.0,>=2.4.1 (from google-cloud-bigquery)
  Downloading google_cloud_core-2.5.0-py3-none-any.whl.metadata (3.1 kB)
Collecting google-resumable-media<3.0.0,>=2.0.0 (from google-cloud-bigquery)
  Downloading google_resumable_media-2.7.2-py2.py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: packaging>=24.2.0 in c:\users\valentina\appdata\roaming\python\python313\site-packages (from google-cloud-bigquery) (25.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in c:\users\valentina\appdata\roaming\python\python313\site-packages (from google-cloud-bigquery) (2.9.0.post0)
Collecting requests<3.0.0,>=2.21.0 (from google-cloud-bigquery)
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting googleapis-common-protos<2.0.0,>=1.56.2 (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading googleapis_common_protos-1.71.0-py3-none-any.whl.metadata (9.4 kB)
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading protobuf-6.33.0-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting proto-plus<2.0.0,>=1.22.3 (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading proto_plus-1.26.1-py3-none-any.whl.metadata (2.2 kB)
Collecting grpcio<2.0.0,>=1.33.2 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading grpcio-1.76.0-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Collecting grpcio-status<2.0.0,>=1.33.2 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading grpcio_status-1.76.0-py3-none-any.whl.metadata (1.1 kB)
Collecting cachetools<7.0,>=2.0.0 (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery)
  Downloading cachetools-6.2.1-py3-none-any.whl.metadata (5.5 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery)
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting rsa<5,>=3.1.4 (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery)
  Downloading rsa-4.9.1-py3-none-any.whl.metadata (5.6 kB)
Collecting google-crc32c<2.0dev,>=1.0 (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery)
  Downloading google_crc32c-1.7.1-cp313-cp313-win_amd64.whl.metadata (2.4 kB)
Collecting typing-extensions~=4.12 (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: six>=1.5 in c:\users\valentina\appdata\roaming\python\python313\site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.17.0)
Collecting charset_normalizer<4,>=2 (from requests<3.0.0,>=2.21.0->google-cloud-bigquery)
  Downloading charset_normalizer-3.4.4-cp313-cp313-win_amd64.whl.metadata (38 kB)
Collecting idna<4,>=2.5 (from requests<3.0.0,>=2.21.0->google-cloud-bigquery)
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3.0.0,>=2.21.0->google-cloud-bigquery)
  Downloading urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.21.0->google-cloud-bigquery)
  Downloading certifi-2025.10.5-py3-none-any.whl.metadata (2.5 kB)
Collecting pyasn1>=0.1.3 (from rsa<5,>=3.1.4->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery)
  Downloading pyasn1-0.6.1-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\valentina\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\valentina\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\valentina\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Downloading google_cloud_bigquery-3.38.0-py3-none-any.whl (259 kB)
Downloading google_api_core-2.28.1-py3-none-any.whl (173 kB)
Downloading google_auth-2.42.1-py2.py3-none-any.whl (222 kB)
Downloading cachetools-6.2.1-py3-none-any.whl (11 kB)
Downloading google_cloud_core-2.5.0-py3-none-any.whl (29 kB)
Downloading google_resumable_media-2.7.2-py2.py3-none-any.whl (81 kB)
Downloading google_crc32c-1.7.1-cp313-cp313-win_amd64.whl (33 kB)
Downloading googleapis_common_protos-1.71.0-py3-none-any.whl (294 kB)
Downloading grpcio-1.76.0-cp313-cp313-win_amd64.whl (4.7 MB)
   ---------------------------------------- 0.0/4.7 MB ? eta -:--:--
   ---------------------------------------- 4.7/4.7 MB 41.6 MB/s  0:00:00
Downloading grpcio_status-1.76.0-py3-none-any.whl (14 kB)
Downloading proto_plus-1.26.1-py3-none-any.whl (50 kB)
Downloading protobuf-6.33.0-cp310-abi3-win_amd64.whl (436 kB)
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.4.4-cp313-cp313-win_amd64.whl (107 kB)
Downloading idna-3.11-py3-none-any.whl (71 kB)
Downloading rsa-4.9.1-py3-none-any.whl (34 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading urllib3-2.5.0-py3-none-any.whl (129 kB)
Downloading certifi-2025.10.5-py3-none-any.whl (163 kB)
Downloading pyasn1-0.6.1-py3-none-any.whl (83 kB)
Downloading pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Installing collected packages: urllib3, typing-extensions, pyasn1, protobuf, idna, google-crc32c, charset_normalizer, certifi, cachetools, rsa, requests, pyasn1-modules, proto-plus, grpcio, googleapis-common-protos, google-resumable-media, grpcio-status, google-auth, google-api-core, google-cloud-core, google-cloud-bigquery

   ----------------------------------------  0/21 [urllib3]
   ----------------------------------------  0/21 [urllib3]
   ----------------------------------------  0/21 [urllib3]
   ----------------------------------------  0/21 [urllib3]
   ----------------------------------------  0/21 [urllib3]
   ----------------------------------------  0/21 [urllib3]
   ----------------------------------------  0/21 [urllib3]
   ----------------------------------------  0/21 [urllib3]
   ----------------------------------------  0/21 [urllib3]
   ----------------------------------------  0/21 [urllib3]
   ----------------------------------------  0/21 [urllib3]
   ----------------------------------------  0/21 [urllib3]
   - --------------------------------------  1/21 [typing-extensions]
   - --------------------------------------  1/21 [typing-extensions]
   --- ------------------------------------  2/21 [pyasn1]
   --- ------------------------------------  2/21 [pyasn1]
   --- ------------------------------------  2/21 [pyasn1]
   --- ------------------------------------  2/21 [pyasn1]
   --- ------------------------------------  2/21 [pyasn1]
   --- ------------------------------------  2/21 [pyasn1]
   --- ------------------------------------  2/21 [pyasn1]
   --- ------------------------------------  2/21 [pyasn1]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ----- ----------------------------------  3/21 [protobuf]
   ------- --------------------------------  4/21 [idna]
   ------- --------------------------------  4/21 [idna]
   ------- --------------------------------  4/21 [idna]
   --------- ------------------------------  5/21 [google-crc32c]
   ----------- ----------------------------  6/21 [charset_normalizer]
   ----------- ----------------------------  6/21 [charset_normalizer]
   ----------- ----------------------------  6/21 [charset_normalizer]
   ----------- ----------------------------  6/21 [charset_normalizer]
   ----------- ----------------------------  6/21 [charset_normalizer]
   ----------- ----------------------------  6/21 [charset_normalizer]
   ------------- --------------------------  7/21 [certifi]
   --------------- ------------------------  8/21 [cachetools]
   --------------- ------------------------  8/21 [cachetools]
   ----------------- ----------------------  9/21 [rsa]
   ----------------- ----------------------  9/21 [rsa]
   ----------------- ----------------------  9/21 [rsa]
   ----------------- ----------------------  9/21 [rsa]
   ----------------- ----------------------  9/21 [rsa]
   ----------------- ----------------------  9/21 [rsa]
   ----------------- ----------------------  9/21 [rsa]
   ----------------- ----------------------  9/21 [rsa]
   ----------------- ----------------------  9/21 [rsa]
   ----------------- ----------------------  9/21 [rsa]
   ----------------- ----------------------  9/21 [rsa]
   ----------------- ----------------------  9/21 [rsa]
   ----------------- ----------------------  9/21 [rsa]
   ----------------- ----------------------  9/21 [rsa]
   ------------------- -------------------- 10/21 [requests]
   ------------------- -------------------- 10/21 [requests]
   ------------------- -------------------- 10/21 [requests]
   ------------------- -------------------- 10/21 [requests]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   -------------------- ------------------- 11/21 [pyasn1-modules]
   ---------------------- ----------------- 12/21 [proto-plus]
   ---------------------- ----------------- 12/21 [proto-plus]
   ---------------------- ----------------- 12/21 [proto-plus]
   ---------------------- ----------------- 12/21 [proto-plus]
   ---------------------- ----------------- 12/21 [proto-plus]
   ------------------------ --------------- 13/21 [grpcio]
   ------------------------ --------------- 13/21 [grpcio]
   ------------------------ --------------- 13/21 [grpcio]
   ------------------------ --------------- 13/21 [grpcio]
   ------------------------ --------------- 13/21 [grpcio]
   ------------------------ --------------- 13/21 [grpcio]
   ------------------------ --------------- 13/21 [grpcio]
   ------------------------ --------------- 13/21 [grpcio]
   ------------------------ --------------- 13/21 [grpcio]
   ------------------------ --------------- 13/21 [grpcio]
   ------------------------ --------------- 13/21 [grpcio]
   ------------------------ --------------- 13/21 [grpcio]
   ------------------------ --------------- 13/21 [grpcio]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   -------------------------- ------------- 14/21 [googleapis-common-protos]
   ---------------------------- ----------- 15/21 [google-resumable-media]
   ---------------------------- ----------- 15/21 [google-resumable-media]
   ---------------------------- ----------- 15/21 [google-resumable-media]
   ---------------------------- ----------- 15/21 [google-resumable-media]
   ---------------------------- ----------- 15/21 [google-resumable-media]
   ---------------------------- ----------- 15/21 [google-resumable-media]
   -------------------------------- ------- 17/21 [google-auth]
   -------------------------------- ------- 17/21 [google-auth]
   -------------------------------- ------- 17/21 [google-auth]
   -------------------------------- ------- 17/21 [google-auth]
   -------------------------------- ------- 17/21 [google-auth]
   -------------------------------- ------- 17/21 [google-auth]
   -------------------------------- ------- 17/21 [google-auth]
   -------------------------------- ------- 17/21 [google-auth]
   -------------------------------- ------- 17/21 [google-auth]
   -------------------------------- ------- 17/21 [google-auth]
   -------------------------------- ------- 17/21 [google-auth]
   -------------------------------- ------- 17/21 [google-auth]
   -------------------------------- ------- 17/21 [google-auth]
   -------------------------------- ------- 17/21 [google-auth]
   -------------------------------- ------- 17/21 [google-auth]
   -------------------------------- ------- 17/21 [google-auth]
   -------------------------------- ------- 17/21 [google-auth]
   -------------------------------- ------- 17/21 [google-auth]
   ---------------------------------- ----- 18/21 [google-api-core]
   ---------------------------------- ----- 18/21 [google-api-core]
   ---------------------------------- ----- 18/21 [google-api-core]
   ---------------------------------- ----- 18/21 [google-api-core]
   ---------------------------------- ----- 18/21 [google-api-core]
   ---------------------------------- ----- 18/21 [google-api-core]
   ---------------------------------- ----- 18/21 [google-api-core]
   ---------------------------------- ----- 18/21 [google-api-core]
   ---------------------------------- ----- 18/21 [google-api-core]
   ---------------------------------- ----- 18/21 [google-api-core]
   ---------------------------------- ----- 18/21 [google-api-core]
   ---------------------------------- ----- 18/21 [google-api-core]
   ---------------------------------- ----- 18/21 [google-api-core]
   ---------------------------------- ----- 18/21 [google-api-core]
   ---------------------------------- ----- 18/21 [google-api-core]
   ------------------------------------ --- 19/21 [google-cloud-core]
   ------------------------------------ --- 19/21 [google-cloud-core]
   -------------------------------------- - 20/21 [google-cloud-bigquery]
   -------------------------------------- - 20/21 [google-cloud-bigquery]
   -------------------------------------- - 20/21 [google-cloud-bigquery]
   -------------------------------------- - 20/21 [google-cloud-bigquery]
   -------------------------------------- - 20/21 [google-cloud-bigquery]
   -------------------------------------- - 20/21 [google-cloud-bigquery]
   -------------------------------------- - 20/21 [google-cloud-bigquery]
   -------------------------------------- - 20/21 [google-cloud-bigquery]
   -------------------------------------- - 20/21 [google-cloud-bigquery]
   -------------------------------------- - 20/21 [google-cloud-bigquery]
   -------------------------------------- - 20/21 [google-cloud-bigquery]
   -------------------------------------- - 20/21 [google-cloud-bigquery]
   -------------------------------------- - 20/21 [google-cloud-bigquery]
   ---------------------------------------- 21/21 [google-cloud-bigquery]


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [49]:
from google.cloud import bigquery

In [3]:
import pandas as pd

Tabla. officials

In [ ]:
officials = pd.read_csv(r"C:\Users\Valentina\OneDrive\Desktop\HENRY\PROYECTO FINAL\ARCHIVOS CSV DE NBA\csv\officials.csv")

In [ ]:
officials.shape

(70971, 5)

In [ ]:
officials.head
officials.tail

<bound method NDFrame.tail of         game_id  official_id first_name  last_name  jersey_num
0      29600059         1140      Bruce  Alexander         9.0
1      29600059         1165       Luis     Grillo         8.0
2      29600059         1153        Joe   Crawford        17.0
3      29600114         1147       Mike   Callahan        24.0
4      29600114         1142       Dick    Bavetta        27.0
...         ...          ...        ...        ...         ...
70966  32200001       200834       Mark    Lindsay        29.0
70967  32200001         1193    Michael      Smith        38.0
70968  32200001       101284       John      Goble        10.0
70969  32200001       200834       Mark    Lindsay        29.0
70970  32200001         1193    Michael      Smith        38.0

[70971 rows x 5 columns]>

In [ ]:
officials.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70971 entries, 0 to 70970
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   game_id      70971 non-null  int64
 1   official_id  70971 non-null  int64
 2   first_name   70971 non-null  object
 3   last_name    70971 non-null  object
 4   jersey_num   70781 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 2.7+ MB

In [ ]:
#Cambiar tipo de dato
officials["game_id"] = officials["game_id"].astype(str)
officials["official_id"] = officials["official_id"].astype(str)

In [17]:
#Diagnóstico de nulos. Función general. 
def diagnostico_nulos(df, nombre=""):
    # se genera un nuevo DataFrame resumenulos con dos columnas: Valores nulos (conteo absoluto) y % de nulos 
    resumenulos = pd.DataFrame({
        "Valores nulos": df.isnull().sum(),
        "% de nulos": 100 * df.isnull().mean()
    })
    # Ordenar de mayor a menor % de nulos
    resumenulos = resumenulos.sort_values("% de nulos", ascending=False)

    # Asignar nombre al índice
    resumenulos.index.name = nombre
    
    return resumenulos

In [ ]:
resumenulos = diagnostico_nulos(officials, "df")
print(resumenulos)

             Valores nulos  % de nulos
df
jersey_num             190    0.267715
game_id                  0    0.000000
official_id              0    0.000000
first_name               0    0.000000
last_name                0    0.000000

In [ ]:
#Análisis descriptivo 
officials.describe()                    # Estadísticas de variables numéricas

         jersey_num
count  70781.000000
mean      39.341857
std       21.700928
min        0.000000
25%       22.000000
50%       38.000000
75%       56.000000
max      166.000000

In [ ]:
officials.describe(include='object')    # Para variables categóricas

         game_id official_id first_name   last_name
count      70971       70971      70971       70971
unique     23575         235        167         197
top     20700367        1162      Scott  Richardson
freq           6        1331       2975        1961

tabla: other_sats

In [21]:
other_stats = pd.read_csv(r"C:\Users\Valentina\OneDrive\Desktop\HENRY\PROYECTO FINAL\ARCHIVOS CSV DE NBA\csv\other_stats.csv")

In [23]:
other_stats.shape

(28271, 26)

In [24]:
other_stats.head
other_stats.tail

<bound method NDFrame.tail of         game_id  league_id  team_id_home team_abbreviation_home  \
0      29600012          0    1610612756                    PHX
1      29600005          0    1610612737                    ATL
2      29600002          0    1610612739                    CLE
3      29600007          0    1610612754                    IND
4      29600013          0    1610612746                    LAC
...         ...        ...           ...                    ...
28266  42200402          0    1610612743                    DEN
28267  42200403          0    1610612748                    MIA
28268  42200404          0    1610612743                    DEN
28269  32200001          0    1610616834                    LBN
28270  32200001          0    1610616834                    LBN

      team_city_home  pts_paint_home  pts_2nd_chance_home  pts_fb_home  \
0            Phoenix              44                   18            2
1            Atlanta              32                    9            6
2          Cleveland              36                   14            6
3            Indiana              34                   11            4
4        Los Angeles              40                   19            2
...              ...             ...                  ...          ...
28266         Denver              50                   15           18
28267          Miami              34                    7           11
28268         Denver              48                    6           12
28269           Team             118                   15           27
28270           Team             118                   15           27

       largest_lead_home  lead_changes  ...  team_abbreviation_away  \
0                      1             4  ...                     LAL
1                      0             0  ...                     MIA
2                     20             1  ...                     NJN
3                     10             7  ...                     DET
4                     12             5  ...                     GSW
...                  ...           ...  ...                     ...
28266                 15             4  ...                     MIA
28267                  5             7  ...                     DEN
28268                 17             3  ...                     MIA
28269                  4            24  ...                     GNS
28270                  4            24  ...                     GNS

       team_city_away  pts_paint_away  pts_2nd_chance_away  pts_fb_away  \
0         Los Angeles              42                   10           13
1               Miami              32                   15           14
2          New Jersey              26                   16            4
3             Detroit              30                   14            7
4        Golden State              30                    9            2
...               ...             ...                  ...          ...
28266           Miami              34                   11            5
28267          Denver              60                   14           11
28268           Miami              46                    9           14
28269            Team              88                   14           33
28270            Team              88                   14           33

       largest_lead_away team_turnovers_away total_turnovers_away  \
0                     19                 0.0                 23.0
1                     16                 1.0                 19.0
2                      2                 1.0                 22.0
3                      9                 2.0                 19.0
4                      6                 0.0                 20.0
...                  ...                 ...                  ...
28266                 12                 0.0                 11.0
28267                 21                 1.0                 14.0
28268                  3                 1.0                 15.0
28269                 19                 0.0                 12.0
28270                 19                 0.0                 12.0

       team_rebounds_away  pts_off_to_away
0                    11.0              NaN
1                     6.0              NaN
2                    12.0              NaN
3                    10.0              NaN
4                     7.0              NaN
...                   ...              ...
28266                 4.0             23.0
28267                 7.0             17.0
28268                 9.0             17.0
28269                 3.0             20.0
28270                 3.0             20.0

[28271 rows x 26 columns]>

In [28]:
print(other_stats.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28271 entries, 0 to 28270
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game_id                 28271 non-null  int64
 1   league_id               28271 non-null  int64
 2   team_id_home            28271 non-null  int64
 3   team_abbreviation_home  28271 non-null  object
 4   team_city_home          28271 non-null  object
 5   pts_paint_home          28271 non-null  int64
 6   pts_2nd_chance_home     28271 non-null  int64
 7   pts_fb_home             28271 non-null  int64
 8   largest_lead_home       28271 non-null  int64
 9   lead_changes            28271 non-null  int64
 10  times_tied              28271 non-null  int64
 11  team_turnovers_home     28269 non-null  float64
 12  total_turnovers_home    27955 non-null  float64
 13  team_rebounds_home      26273 non-null  float64
 14  pts_off_to_home         26148 non-null  float64
 15  team_id_away            28271 non-null  int64
 16  team_abbreviation_away  28271 non-null  object
 17  team_city_away          28271 non-null  object
 18  pts_paint_away          28271 non-null  int64
 19  pts_2nd_chance_away     28271 non-null  int64
 20  pts_fb_away             28271 non-null  int64
 21  largest_lead_away       28271 non-null  int64
 22  team_turnovers_away     28269 non-null  float64
 23  total_turnovers_away    27955 non-null  float64
 24  team_rebounds_away      26273 non-null  float64
 25  pts_off_to_away         26148 non-null  float64
dtypes: float64(8), int64(14), object(4)
memory usage: 5.6+ MB
None

In [35]:
#Cambiar tipo de dato
other_stats["game_id"] = other_stats["game_id"].astype(str)
other_stats["league_id"] = other_stats["league_id"].astype(str)
other_stats["team_id_home"] = other_stats["team_id_home"].astype(str)
other_stats["team_id_away"] = other_stats ["team_id_away"].astype(str)

In [29]:
resumenulos = diagnostico_nulos(other_stats, "df")
print(resumenulos)

                        Valores nulos  % de nulos
df
pts_off_to_away                  2123    7.509462
pts_off_to_home                  2123    7.509462
team_rebounds_home               1998    7.067313
team_rebounds_away               1998    7.067313
total_turnovers_away              316    1.117753
total_turnovers_home              316    1.117753
team_turnovers_home                 2    0.007074
team_turnovers_away                 2    0.007074
game_id                             0    0.000000
league_id                           0    0.000000
lead_changes                        0    0.000000
largest_lead_home                   0    0.000000
pts_fb_home                         0    0.000000
pts_2nd_chance_home                 0    0.000000
pts_paint_home                      0    0.000000
team_city_home                      0    0.000000
team_abbreviation_home              0    0.000000
team_id_home                        0    0.000000
team_city_away                      0    0.000000
team_abbreviation_away              0    0.000000
team_id_away                        0    0.000000
times_tied                          0    0.000000
largest_lead_away                   0    0.000000
pts_fb_away                         0    0.000000
pts_2nd_chance_away                 0    0.000000
pts_paint_away                      0    0.000000

In [ ]:
#Análisis descriptivo 
other_stats.describe()                    # Estadísticas de variables numéricas

,pts_paint_home,pts_2nd_chance_home,pts_fb_home,largest_lead_home,lead_changes,times_tied,team_turnovers_home,total_turnovers_home,team_rebounds_home,pts_off_to_home,pts_paint_away,pts_2nd_chance_away,pts_fb_away,largest_lead_away,team_turnovers_away,total_turnovers_away,team_rebounds_away,pts_off_to_away
count,28271.000000,28271.000000,28271.000000,28271.000000,28271.000000,28271.000000,28269.000000,27955.000000,26273.000000,26148.000000,28271.000000,28271.000000,28271.000000,28271.000000,28269.000000,27955.000000,26273.000000,26148.000000
mean,41.904496,13.243889,13.006119,11.949383,6.075378,5.098086,0.628745,14.564192,8.456971,15.227551,41.658307,13.328145,12.882424,11.641046,0.633344,14.595421,8.461006,15.329050
std,10.566933,5.405389,6.675118,9.148112,5.287184,4.105700,0.808296,4.046174,3.132525,7.116555,10.450258,5.402271,6.544709,9.010137,0.820544,4.063812,3.105498,7.195931
min,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,8.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000
25%,34.000000,9.000000,8.000000,5.000000,2.000000,2.000000,0.000000,12.000000,6.000000,11.000000,34.000000,10.000000,8.000000,5.000000,0.000000,12.000000,6.000000,11.000000
50%,42.000000,13.000000,12.000000,10.000000,5.000000,4.000000,0.000000,14.000000,8.000000,15.000000,42.000000,13.000000,12.000000,10.000000,0.000000,14.000000,8.000000,15.000000
75%,48.000000,17.000000,17.000000,17.000000,9.000000,8.000000,1.000000,17.000000,10.000000,20.000000,48.000000,17.000000,17.000000,17.000000,1.000000,17.000000,10.000000,20.000000
max,120.000000,37.000000,106.000000,70.000000,40.000000,29.000000,6.000000,34.000000,27.000000,47.000000,108.000000,38.000000,107.000000,78.000000,7.000000,33.000000,24.000000,44.000000

In [37]:
other_stats.describe(include='object')    # Para variables categóricas

,game_id,league_id,team_id_home,team_abbreviation_home,team_city_home,team_id_away,team_abbreviation_away,team_city_away
count,28271,28271,28271,28271,28271,28271,28271,28271
unique,28261,1,49,58,54,45,56,50
top,30200001,0,1610612738,BOS,Los Angeles,1610612748,MIA,Los Angeles
freq,2,28271,1035,1035,1633,1033,1033,1628

Tabla: player

In [40]:
player = pd.read_csv(r"C:\Users\Valentina\OneDrive\Desktop\HENRY\PROYECTO FINAL\ARCHIVOS CSV DE NBA\csv\player.csv")

In [41]:
player.shape

(4831, 5)

In [42]:
player.head
player.tail

<bound method NDFrame.tail of            id            full_name first_name     last_name  is_active
0       76001       Alaa Abdelnaby       Alaa     Abdelnaby          0
1       76002      Zaid Abdul-Aziz       Zaid    Abdul-Aziz          0
2       76003  Kareem Abdul-Jabbar     Kareem  Abdul-Jabbar          0
3          51   Mahmoud Abdul-Rauf    Mahmoud    Abdul-Rauf          0
4        1505    Tariq Abdul-Wahad      Tariq   Abdul-Wahad          0
...       ...                  ...        ...           ...        ...
4826  1627790           Ante Zizic       Ante         Zizic          0
4827    78647             Jim Zoet        Jim          Zoet          0
4828    78648            Bill Zopf       Bill          Zopf          0
4829  1627826          Ivica Zubac      Ivica         Zubac          1
4830    78650           Matt Zunic       Matt         Zunic          0

[4831 rows x 5 columns]>

In [43]:
player.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4831 entries, 0 to 4830
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          4831 non-null   int64
 1   full_name   4831 non-null   object
 2   first_name  4825 non-null   object
 3   last_name   4831 non-null   object
 4   is_active   4831 non-null   int64
dtypes: int64(2), object(3)
memory usage: 188.8+ KB

In [44]:
#cambiar tipos de datos.
player["id"] = player["id"].astype(str)
player["is_active"] = player["is_active"].astype(bool)

In [46]:
resumenulos = diagnostico_nulos(player, "df")
print(resumenulos)

            Valores nulos  % de nulos
df
first_name              6    0.124198
id                      0    0.000000
full_name               0    0.000000
last_name               0    0.000000
is_active               0    0.000000

In [ ]:
#Análisis descriptivo. Solo variables categóricas. 
player.describe()

           id       full_name first_name last_name is_active
count    4831            4831       4825      4831      4831
unique   4831            4791       1568      2904         2
top     76001  George Johnson       John  Williams     False
freq        1               3         87        78      4249

Tabla: play by play

In [5]:
pbp = pd.read_csv(r"C:\Users\Valentina\Downloads\archive (1)\csv\play_by_play.csv")

In [51]:
pbp.shape

(13592899, 34)

In [52]:
pbp.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13592899 entries, 0 to 13592898
Data columns (total 34 columns):
 #   Column                     Dtype
---  ------                     -----
 0   game_id                    int64
 1   eventnum                   int64
 2   eventmsgtype               int64
 3   eventmsgactiontype         int64
 4   period                     int64
 5   wctimestring               object
 6   pctimestring               object
 7   homedescription            object
 8   neutraldescription         object
 9   visitordescription         object
 10  score                      object
 11  scoremargin                object
 12  person1type                float64
 13  player1_id                 int64
 14  player1_name               object
 15  player1_team_id            float64
 16  player1_team_city          object
 17  player1_team_nickname      object
 18  player1_team_abbreviation  object
 19  person2type                float64
 20  player2_id                 int64
 21  player2_name               object
 22  player2_team_id            float64
 23  player2_team_city          object
 24  player2_team_nickname      object
 25  player2_team_abbreviation  object
 26  person3type                float64
 27  player3_id                 int64
 28  player3_name               object
 29  player3_team_id            float64
 30  player3_team_city          object
 31  player3_team_nickname      object
 32  player3_team_abbreviation  object
 33  video_available_flag       int64
dtypes: float64(6), int64(9), object(19)
memory usage: 3.4+ GB

In [ ]:
#cambiar el tipo de datoss

In [53]:
resumenulos = diagnostico_nulos(pbp, "df")
print(resumenulos)

                           Valores nulos  % de nulos
df
neutraldescription              13273327   97.648978
player3_name                    13251785   97.490499
player3_team_nickname           13246931   97.454789
player3_team_abbreviation       13246931   97.454789
player3_team_city               13246931   97.454789
player3_team_id                 13246931   97.454789
scoremargin                     10028436   73.777021
score                           10028436   73.777021
player2_name                     9683745   71.241205
player2_team_city                9660454   71.069858
player2_team_abbreviation        9660454   71.069858
player2_team_id                  9660454   71.069858
player2_team_nickname            9660454   71.069858
visitordescription               6634527   48.808771
homedescription                  6530241   48.041562
player1_team_id                  1215858    8.944803
player1_team_nickname            1215858    8.944803
player1_team_city                1215858    8.944803
player1_team_abbreviation        1215858    8.944803
player1_name                     1208875    8.893430
person1type                         3298    0.024263
wctimestring                         950    0.006989
eventnum                               0    0.000000
game_id                                0    0.000000
period                                 0    0.000000
pctimestring                           0    0.000000
player1_id                             0    0.000000
eventmsgactiontype                     0    0.000000
eventmsgtype                           0    0.000000
player2_id                             0    0.000000
person2type                            0    0.000000
player3_id                             0    0.000000
person3type                            0    0.000000
video_available_flag                   0    0.000000

In [6]:
#Análisis descriptivo 
pbp.describe()                    # Estadísticas de variables numéricas

,game_id,eventnum,eventmsgtype,eventmsgactiontype,period,person1type,player1_id,player1_team_id,person2type,player2_id,player2_team_id,person3type,player3_id,player3_team_id,video_available_flag
count,1.359290e+07,1.359290e+07,1.359290e+07,1.359290e+07,1.359290e+07,1.358960e+07,1.359290e+07,1.237704e+07,1.359290e+07,1.359290e+07,3.932445e+06,1.359290e+07,1.359290e+07,3.459680e+05,1.359290e+07
mean,2.324102e+07,2.725295e+02,3.975202e+00,9.359604e+00,2.548225e+00,4.265943e+00,1.074050e+08,1.609433e+09,1.303011e+00,2.626129e+05,1.609255e+09,2.248237e-01,3.246051e+05,1.609900e+09,2.766433e-01
std,5.810142e+06,1.668649e+02,2.618653e+00,2.094391e+01,1.139473e+00,9.439848e-01,4.014578e+08,4.357649e+07,2.059785e+00,1.793227e+07,4.674989e+07,7.597816e-01,2.266589e+07,3.386263e+07,4.473386e-01
min,1.130000e+07,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,4.100000e+01,0.000000e+00,0.000000e+00,4.100000e+01,0.000000e+00,0.000000e+00,4.100000e+01,0.000000e+00
25%,2.060058e+07,1.310000e+02,2.000000e+00,0.000000e+00,2.000000e+00,4.000000e+00,1.517000e+03,1.610613e+09,0.000000e+00,0.000000e+00,1.610613e+09,0.000000e+00,0.000000e+00,1.610613e+09,0.000000e+00
50%,2.140070e+07,2.660000e+02,4.000000e+00,1.000000e+00,3.000000e+00,4.000000e+00,1.011080e+05,1.610613e+09,0.000000e+00,0.000000e+00,1.610613e+09,0.000000e+00,0.000000e+00,1.610613e+09,0.000000e+00
75%,2.210043e+07,4.000000e+02,5.000000e+00,5.000000e+00,4.000000e+00,5.000000e+00,2.034580e+05,1.610613e+09,4.000000e+00,8.960000e+02,1.610613e+09,0.000000e+00,0.000000e+00,1.610613e+09,1.000000e+00
max,4.980009e+07,1.018000e+03,1.800000e+01,1.100000e+02,8.000000e+00,7.000000e+00,1.966938e+09,1.610617e+09,7.000000e+00,1.966938e+09,1.610617e+09,5.000000e+00,1.962938e+09,1.610617e+09,1.000000e+00

In [7]:
pbp.describe(include='object')    # Para variables categóricas

,wctimestring,pctimestring,homedescription,neutraldescription,visitordescription,score,scoremargin,player1_name,player1_team_city,player1_team_nickname,player1_team_abbreviation,player2_name,player2_team_city,player2_team_nickname,player2_team_abbreviation,player3_name,player3_team_city,player3_team_nickname,player3_team_abbreviation
count,13591949,13592899,7062658,319572,6958372,3564463,3564463,12384024,12377041,12377041,12377041,3909154,3932445,3932445,3932445,341114,345968,345968,345968
unique,4128,721,1837935,18790,1788728,11546,146,2941,56,58,62,2912,56,58,62,2396,54,56,60
top,9:01 PM,0:00,LAKERS Rebound,Timeout: Official,Lakers Rebound,0 - 2,2,LeBron James,Los Angeles,Lakers,LAL,LeBron James,Los Angeles,Celtics,BOS,Tim Duncan,Los Angeles,Spurs,SAS
freq,54099,283673,9778,33959,9150,12854,171891,63060,712799,439999,439999,23730,216063,146149,146149,3175,21798,13665,13665